### PR TITLE
Rotface slime spray

### PR DESCRIPTION
**Pull request by dufernst**
Rotface should face the ooze spray stalker when casting slime spray.

### CODE REVIEW

**Comment by dufernst** [comment]
I'll look into that, thanks for the feedback. :)

**Comment by carlos93** [comment]
I can correct in core it. Thanks for post it ;)

**Comment by dufernst** [comment]
k awesome ty :)

**Comment by rsa** [comment]
not need core work. use spell_linked table for this with type SPELL_LINKED_TYPE_TRIGGERED         = 4

**Pull request closed without merging**
