### PR TITLE
nexus and RS

### PR DESCRIPTION
**Pull request by simplexo**

### CODE REVIEW

**Comment by ghost** [comment]
the quest are there to do if you want but not require yet

**Comment by rsa** [comment]
yoyr may open requests separate (or commit yourself?) spellhacks in Oculus need remove, but not copy from one version to next...

**Comment by ghost** [comment]
haven t been able to commit myself since name change and spell hacks were from old version left intact 8P

**Comment by ghost** [comment]
maybe u need to readd me or something ive been dropping hints for weeks its X0  but the 0 = number zero

**Pull request closed without merging**
