### PR TITLE
Ulduar

### PR DESCRIPTION
**Pull request by XanderMld**
Fix Text & Tab

### CODE REVIEW

**Comment by Reamer** [comment]
Are the scripttexts confirm with sd2?
SQL querys are crap. don't use REPLACE
Why you make "/_mechanic_immune_mask=583745371,_/"?
Plz change the sql diff to DELETE ... INSERT ...

**Comment by Reamer** [comment]
the script changes look okay

**Comment by raynar** [comment]
so merge reamer?

**Comment by Reamer** [comment]
@raynar No the sql files need a rewrite.
For example this lines are crap

```
UPDATE creature_template SET unit_flags = 0, mechanic_immune_mask = 619397115, ScriptName = boss_general_vezax' WHERE entry = 33271;
UPDATE creature_template SET MinHealth = 23009250, MaxHealth = 23009250, mechanic_immune_mask = 619397115, ScriptName = 'boss_general_vezax' WHERE entry = 33449;
```

**Comment by XanderMld** [comment]
Temp close, need rewrite.

**Pull request closed without merging**
